# Generated by Django 3.0.8 on 2020-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Adresse',
            field=models.CharField(default='', max_length=150),
        ),
    ]
